Bump commons-configuration2 and -text versions
I bumped `commons-configuration2` to 2.7 from 2.2 to address
https://nvd.nist.gov/vuln/detail/CVE-2020-1953.

This also required bumping `commons-text` to 1.9 from 1.2 in order to
remediate a `NoClassDefFoundError` that came up after bumping
`commons-configuration2` alone.