Fix argument processor exception from SetCommand:
java.lang.RuntimeException: Can't create argument processor for type class org.cyclopsgroup.jmxterm.cmd.SetCommand with parser org.cyclopsgroup.jcli.GnuParser@5143a680
Caused by: java.lang.IllegalArgumentException: Can't find constructor with string for type interface java.util.List
Caused by: java.lang.NoSuchMethodException: java.util.List.<init>(java.lang.String)